### ISSUE TITLE
翻译不全的问题

### ISSUE THREAD

**Issue by showgood163** [AisekuOu/Translator#1]
感谢作者的辛苦付出！

这里要反映两个问题。

1.翻译不全。
有些时候，翻译结果只包括第一句的。截图如下。
https://i.loli.net/2020/03/02/rYhDxEpegHdZq6c.png
这个问题有时候也体现为翻译结果只包括第一行的句子。截图如下。
https://i.loli.net/2020/03/02/8E1Fm7fWgOQBRIG.png

我使用的是百度OCR+翻译。请问这个问题的原因是？该怎么DEBUG？

2.文字的背景在晃的时候貌似软件不会作出截图动作，当然此时文字是稳定的。

再次感谢作者！

**Comment by AisekuOu** [comment]
> 感谢作者的辛苦付出！
> 
> 这里要反映两个问题。
> 
> 1.翻译不全。
> 有些时候，翻译结果只包括第一句的。截图如下。
> https://i.loli.net/2020/03/02/rYhDxEpegHdZq6c.png
> 这个问题有时候也体现为翻译结果只包括第一行的句子。截图如下。
> https://i.loli.net/2020/03/02/8E1Fm7fWgOQBRIG.png
> 
> 我使用的是百度OCR+翻译。请问这个问题的原因是？该怎么DEBUG？
> 
> 2.文字的背景在晃的时候貌似软件不会作出截图动作，当然此时文字是稳定的。
> 
> 再次感谢作者！

能否将问题1发生时的文件目录下的trans.png文件反馈到此页呢

Debug的话在其它设置页有一个Log选项，开启后进行翻译时会把Log信息记录在文件目录下的Log.txt文件中

背景晃动时软件会一直认为文字在变动，此方案无法像VNR那样去真正捕捉文字句柄，只能不停对比当前截图是否保持不变后认为文字已经显示完毕，建议使用单次扫描功能，单次扫描功能是手动触发，在文字背景为动态下适用

**Comment by showgood163** [comment]
关于第一个问题

这里重新截图了，trans和翻译结果如下
https://i.loli.net/2020/03/03/Nl8taFbI1LEocSJ.png
https://i.loli.net/2020/03/03/klZ69Y2gFdNLt5A.png

**Comment by AisekuOu** [comment]
> 关于第一个问题
> 
> 这里重新截图了，trans和翻译结果如下
> https://i.loli.net/2020/03/03/Nl8taFbI1LEocSJ.png
> https://i.loli.net/2020/03/03/klZ69Y2gFdNLt5A.png

抱歉 最近一直很忙 我会尽快处理的

**Comment by AisekuOu** [comment]
> 关于第一个问题
> 
> 这里重新截图了，trans和翻译结果如下
> https://i.loli.net/2020/03/03/Nl8taFbI1LEocSJ.png
> https://i.loli.net/2020/03/03/klZ69Y2gFdNLt5A.png

Sorry for late, 最近在工作 所以 忙不过来 我找到原因了 应该是api接口设置的时候设置为默认 并没有设置为多行
